version: "3.9"

services:
  backend:
    container_name: anchor-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SSL: ${DATABASE_SSL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "3001:3001"

  # frontend:
  #   container_name: anchor-frontend
  #   build:
  #     context: ./web-frontend/anchor-web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./web-frontend/anchor-web:/app

volumes:
  anchor_data:
  pgadmin_data:
