version: "3.9"

services:
  backend:
    container_name: anchor-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SSL: ${DATABASE_SSL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      GOOGLE_GMAIL_CALLBACK_URL: ${GOOGLE_GMAIL_CALLBACK_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}
      MAILJET_FROM_EMAIL: ${MAILJET_FROM_EMAIL}
      MAILJET_FROM_NAME: ${MAILJET_FROM_NAME}

    ports:
      - "3001:3001"

  # frontend:
  #   container_name: anchor-frontend
  #   build:
  #     context: ./web-frontend/anchor-web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./web-frontend/anchor-web:/app

volumes:
  anchor_data:
  pgadmin_data:
