services:
  backend:
    container_name: anchor-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SSL: ${DATABASE_SSL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      GOOGLE_GMAIL_CALLBACK_URL: ${GOOGLE_GMAIL_CALLBACK_URL}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_SECRET_KEY: ${MAILJET_SECRET_KEY}
      MAILJET_FROM_EMAIL: ${MAILJET_FROM_EMAIL}
      MAILJET_FROM_NAME: ${MAILJET_FROM_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]

  frontend:
    container_name: anchor-frontend
    build:
      context: ./web-frontend/anchor-web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_WEBSITE_URL: ${NEXT_PUBLIC_WEBSITE_URL}
    volumes:
      - ./web-frontend/anchor-web:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  website:
    container_name: anchor-website
    build:
      context: ./web-frontend/website
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
    volumes:
      - ./web-frontend/website:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "-p", "3002"]

volumes:
  anchor_data:
  pgadmin_data:
