FROM node:18-alpine

WORKDIR /app

# Install Nest CLI globally for hot reload
RUN npm install -g @nestjs/cli

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3001
CMD ["npm", "run", "start:dev"]
