export const ONBOARDING_STEPS = [
  {
    id: 'resume-upload',
    title: 'Upload Resume',
    subtitle: "Let's start with the basics.",
    isUpload: true,
    options: [],
  },
  {
    id: 'primary-focus',
    title: 'Primary Focus',
    subtitle: 'Choose the direction that excites you most.',
    options: [
      'Find a new job',
      'Switch careers',
      'Get promoted',
      'Learn new skills',
      'Network more',
      'Prepare for interviews',
    ],
  },
  {
    id: 'current-status',
    title: 'Current Status',
    subtitle: 'Where do you currently stand?',
    options: [
      'Actively job searching',
      'Passively looking',
      'Recently laid off',
      'Employed, seeking change',
      'Student/Recent graduate',
      'Career break',
    ],
  },
  {
    id: 'preferred-role',
    title: 'Preferred Role(s)',
    subtitle: 'What position are you aiming for?',
    customHeader: 'What role are you actively working towards right now?',
    isInterest: true,
    options: [
      'Software Engineer',
      'Backend Developer',
      'Full Stack Developer',
      'Data Analyst',
      'AI/ML Engineer',
      'Electrical Engineer',
    ],
  },
  {
    id: 'areas-interest',
    title: 'Areas of Interest',
    subtitle: 'Which industries excite you?',
    isInterest: true,
    options: [
      'Computer Science',
      'Business Administration',
      'Mechanical Engineering',
      'Cybersecurity',
      'Entrepreneurship',
    ],
  },
  {
    id: 'employment-type',
    title: 'Employment Type',
    subtitle: 'How do you want to work?',
    customHeader: 'What kind of work are you looking for?',
    options: [
      'Full-time',
      'Part-time',
      'Internship / Co-op',
      'Freelance / Contract',
    ],
  },
];
