export const ONBOARDING_STEPS = [
  {
    id: 'resume-upload',
    title: 'Upload Resume',
    isUpload: true,
    options: [],
  },
  {
    id: 'primary-focus',
    title: 'Primary Focus',
    options: [
      'Find a new job',
      'Switch careers',
      'Get promoted',
      'Learn new skills',
      'Network more',
      'Prepare for interviews',
    ],
  },
  {
    id: 'current-status',
    title: 'Current Status',
    options: [
      'Actively job searching',
      'Passively looking',
      'Recently laid off',
      'Employed, seeking change',
      'Student/Recent graduate',
      'Career break',
    ],
  },
  {
    id: 'preferred-role',
    title: 'Preferred Role(s)',
    customHeader: 'What role are you actively working towards right now?',
    options: [
      'Frontend Developer',
      'Data Analyst',
      'Product Manager',
      'iOS Engineer',
      'AI/ML Engineer',
      'Backend Developer',
      'QA/Test Automation',
      'Full Stack Developer',
    ],
  },
  {
    id: 'areas-interest',
    title: 'Areas of Interest',
    isInterest: true,
    options: [
      'FinTech',
      'HealthTech',
      'EdTech',
      'Cybersecurity',
      'Ecommerce',
      'Entrepreneurship',
    ],
  },
  {
    id: 'employment-type',
    title: 'Employment Type',
    customHeader: 'What kind of work are you looking for?',
    options: [
      'Full-time',
      'Part-time',
      'Internship / Co-op',
      'Freelance / Contract',
      'Remote only',
      'Hybrid',
      'Onsite',
    ],
  },
];
